
const shoesData = [
       {
        title:'running-red-1',
        category:'running',
        company:'nike',
        img:`${process.env.PUBLIC_URL}/Shoes/running-red-1.jpg`,
        color:'red',
        prize:200
    },
     {
        title:'running-red-2',
        category:'running',
        company:'smart',
        img:'../public/Shoes/running-red-2.jpg',
        color:'red',
        prize:200
    },
     {
        title:'running-red-3',
        category:'running',
        company:'adidas',
        img:'../public/Shoes/running-red-3.jpg',
        color:'red',
        prize:130
    },
    
     {
        title:'football-white-2',
        category:'football',
        company:'nike',
        img:'../public/Shoes/football-white-2.jpg',
        color:'white',
        prize:150
    },
     {
        title:'football-red-1',
        category:'football',
        company:'adidas',
        img:'../public/Shoes/football-red-1.jpg',
        color:'red',
        prize:75
    },
     {
        title:'football-red-2',
        category:'football',
        company:'smart',
        img:'../public/Shoes/football-red-2.jpg',
        color:'red',
        prize:100
    },
     {
        title:'running-black-1',
        category:'running',
        company:'smart',
        img:'../public/Shoes/running-black-1.jpg',
        color:'black',
        prize:120
    },
     {
        title:'running-black-2',
        category:'running',
        company:'smart',
        img:'../public/Shoes/running-black-2.jpg',
        color:'black',
        prize:120
    },
     {
        title:'running-black-3',
        category:'running',
        company:'smart',
        img:'../public/Shoes/running-black-3.jpg',
        color:'black',
        prize:135
    },
     {
        title:'running-black-4',
        category:'running',
        company:'adidas',
        img:'../public/Shoes/running-black-4.jpg',
        color:'black',
        prize:200
    },
  
     {
        title:'running-red-4',
        category:'running',
        company:'nike',
        img:'../public/Shoes/running-red-4.jpg',
        color:'red',
        prize:135
    },
     {
        title:'running-white-1',
        category:'running',
        company:'nike',
        img:'../public/Shoes/running-white-1.jpg',
        color:'white',
        prize:15
    },
    {
        title:'chapals-white-1',
        category:'chapal',
        company:'adidas',
        img:'../public/Shoes/chapals-white-1.jpg',
        color:'white',
        prize:25
    },
    {
        title:'chapals-white-2',
        category:'chapal',
        company:'adidas',
        img:'../public/Shoes/chapals-white-2.jpg',
        color:'white',
        prize:75,
    },
     {
        title:'chapals-white-3',
        category:'chapal',
        company:'nike',
        img:'../public/Shoes/chapals-white-3.jpg',
        color:'white',
        prize:49,
    },
     {
        title:'football-black-1',
        category:'football',
        company:'adidas',
        img:'../public/Shoes/football-black-1.jpg',
        color:'black',
        prize:100
    },
     {
        title:'football-black-2',
        category:'football',
        company:'nike',
        img:'../public/Shoes/football-black-2.jpg',
        color:'black',
        prize:150
    },
     {
        title:'football-black-4',
        category:'football',
        company:'smart',
        img:'../public/Shoes/football-black-4.jpg',
        color:'black',
        prize:220
    },
     {
        title:'football-black-5',
        category:'football',
        company:'adidas',
        img:'../public/Shoes/football-black-5.jpg',
        color:'black',
        prize:150
    },
     {
        title:'football-black-6',
        category:'football',
        company:'adidas',
        img:'../public/Shoes/football-black-6.jpg',
        color:'black',
        prize:175
    },
     {
        title:'running-white-2',
        category:'running',
        company:'smart',
        img:'../public/Shoes/running-white-2.jpg',
        color:'white',
        prize:25
    },
]

export default shoesData